[package]
name = "rs-x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tweety-rs = "0.1.5"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
dotenvy = "0.15"
